# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - project3-de(master)

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://crcommonscience.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_6bdc7386f5214acc9bd02b43453f53f2 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_e0400d5529d9437da8be03aa7eb02d0f }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: crcommonscience.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_6bdc7386f5214acc9bd02b43453f53f2 }}/crcommonscience/latest:${{ github.sha }}
        context: ./data_analysis
        file: ./data_analysis/Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'master'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'project3-de'
        slot-name: 'master'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_e12a6cc5c693462da82d9906096642dc }}
        images: 'crcommonscience.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_6bdc7386f5214acc9bd02b43453f53f2 }}/crcommonscience/latest:${{ github.sha }}'
